### ISSUE TITLE
Test suite no longer builds with hspec >= 2.8

### ISSUE THREAD

**Issue by sternenseemann** [yi-editor/yi#1124]
For example `yi-language`:

```
test/Spec.hs:36:3-10: error:
    Variable not in scope:
      describe
        :: String
           -> m0 b0 -> hspec-core-2.8.5:Test.Hspec.Core.Spec.Monad.Spec
   |
36 |   describe "reversePattern" $ do
   |   ^^^^^^^^

test/Spec.hs:37:5-6: error:
    • Variable not in scope:
        it
          :: String
             -> Either
                  parsec-3.1.14.0:Text.Parsec.Error.ParseError
                  (Pattern, (GroupIndex, DoPa))
             -> t4
    • Perhaps you meant ‘id’ (imported from Prelude)
   |
37 |     it "reverses normal characters" $
   |     ^^

test/Spec.hs:39:9-18: error:
    Variable not in scope:
      shouldBe
        :: t4
           -> Either
                parsec-3.1.14.0:Text.Parsec.Error.ParseError
                (Pattern, (GroupIndex, DoPa))
           -> m0 a3
   |
39 |         `shouldBe` (first ignoreDoPa <$> parseRegex "ba")
   |         ^^^^^^^^^^

test/Spec.hs:41:5-6: error:
    • Variable not in scope:
        it
          :: String
             -> Either
                  parsec-3.1.14.0:Text.Parsec.Error.ParseError
                  (Pattern, (GroupIndex, DoPa))
             -> t3
    • Perhaps you meant ‘id’ (imported from Prelude)
   |
41 |     it "changes carat to dollar" $
   |     ^^

test/Spec.hs:42:43-52: error:
    Variable not in scope:
      shouldBe
        :: t3
           -> Either
                parsec-3.1.14.0:Text.Parsec.Error.ParseError
                (Pattern, (GroupIndex, DoPa))
           -> m0 a2
   |
42 |       (reversePattern <$> parseRegex "^") `shouldBe` parseRegex "$"
   |                                           ^^^^^^^^^^

test/Spec.hs:44:5-6: error:
    • Variable not in scope:
        it
          :: String
             -> Either
                  parsec-3.1.14.0:Text.Parsec.Error.ParseError
                  (Pattern, (GroupIndex, DoPa))
             -> t2
    • Perhaps you meant ‘id’ (imported from Prelude)
   |
44 |     it "changes dollar to carat" $
   |     ^^

test/Spec.hs:45:43-52: error:
    Variable not in scope:
      shouldBe
        :: t2
           -> Either
                parsec-3.1.14.0:Text.Parsec.Error.ParseError
                (Pattern, (GroupIndex, DoPa))
           -> m0 a1
   |
45 |       (reversePattern <$> parseRegex "$") `shouldBe` parseRegex "^"
   |                                           ^^^^^^^^^^

test/Spec.hs:47:5-6: error:
    • Variable not in scope: it :: String -> Property -> m0 a0
    • Perhaps you meant ‘id’ (imported from Prelude)
   |
47 |     it "forms the identity when applied twice" $
   |     ^^

test/Spec.hs:48:75-84: error:
    Variable not in scope:
      shouldBe
        :: Either
             parsec-3.1.14.0:Text.Parsec.Error.ParseError
             (Pattern, (GroupIndex, DoPa))
           -> Either
                parsec-3.1.14.0:Text.Parsec.Error.ParseError
                (Pattern, (GroupIndex, DoPa))
           -> t1
   |
48 |       property $ \p -> (reversePattern . reversePattern <$> parseRegex p) `shouldBe` parseRegex p
   |                                                                           ^^^^^^^^^^

test/Spec.hs:50:5-6: error:
    • Variable not in scope:
        it
          :: String
             -> Either
                  parsec-3.1.14.0:Text.Parsec.Error.ParseError
                  (Pattern, (GroupIndex, DoPa))
             -> t0
    • Perhaps you meant ‘id’ (imported from Prelude)
   |
50 |     it "recursively reverses patterns" $
   |     ^^

test/Spec.hs:52:9-18: error:
    Variable not in scope:
      shouldBe
        :: t0
           -> Either
                parsec-3.1.14.0:Text.Parsec.Error.ParseError
                (Pattern, (GroupIndex, DoPa))
           -> m0 b0
   |
52 |         `shouldBe` (first ignoreDoPa <$> parseRegex "oof|rab")
   |         ^^^^^^^^^^
```

**Comment by josephcsible** [comment]
Turns out it was actually tasty-hspec >= 1.1.7 that was making it break, not hspec >= 2.8. Anyway, #1138 will fix it.
